{{- define "commonlib.serviceAccount.tpl" -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
{{ template "commonlib.metadata" . }}
{{- end }}
{{- end -}}
{{- define "commonlib.serviceAccount" -}}
{{- template "commonlib.util.merge" (append . "commonlib.serviceAccount.tpl") -}}
{{- end -}}